### PR TITLE
Update .NET installer URLs in the installation script

### PR DESCRIPTION
**Pull request by xcasxcursex**
Literally my firs time using git. (We don't use it at work, so....) 
Please correct any errors as necessary.

I note that the newline at the end of the file has been removed. That was not done manually, so something did that automatically.

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Merged, thanks.

**Comment by xcasxcursex** [comment]
Now that we have done this, there will probably be a 3.1.3.1 hotfix released in 1 hour ;)

I notice you made some slight changes to those last lines, was that something I did wrong, or just a chance for an upgrade? Just asking so that I can be more helpful in future.

**Comment by Tyrrrz** [comment]
Haha.

It was just that your branch was somehow 2 commits behind (I have made changes to that file) so there was a conflict between your branch and master. So I edited your files to resolve the conflict.

**Comment by xcasxcursex** [comment]
I thought I made that branch from the fork from your master. Must be my noob mistake. Apologies, will pay extra attention next time.

**Comment by Tyrrrz** [comment]
Your master was actually in-sync with my master, but your `xcasxcursex:LTS-Runtimes-1` branch somehow wasn't. Not sure how that happened.

**Pull request merged**
