### PR TITLE
Add proxy handling for Web requests

### PR DESCRIPTION
**Pull request by monoludic**
Hi,
I use your (nice) app behind a proxy at work and could not use internet connection. I decided to add proxy handling for Web requests through HTTP_PROXY environment variable.

Just add proxy address and credentials if needed in HTTP_PROXY environment variable following the pattern: [http://][user:password@]host[:port]

I'd rather use the environment more than the settings file since the proxy is used by several apps and can be switched on/off or modified easily.

What's working: geo info, solar info, check for update
What's not working: flag retrieval (Uri binding in xaml)

It may be useful for others !

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Have you tried setting `WebRequest.DefaultWebProxy` instead? It might also be able take care of the flag retrieval.

**Comment by monoludic** [comment]
Yes I began with this. It retrieves the network proxy settings defined in Windows Internet Options. Although it stores only the proxy address, not the credentials. I'm behind an authenticated proxy, so I need both.

**Comment by Tyrrrz** [comment]
What I meant was _setting_ `WebRequest.DefaultWebProxy` to the value you parse from the environment variable, instead of setting `httpClientHandler.Proxy`. That way (in theory) the proxy should affect everything that uses WebRequest, which, I think, includes the XAML bindings too.

**Comment by Tyrrrz** [comment]
Also apparently the reason it didn't apply stored credentials when you tried to get proxy from IE was because `UseDefaultProxy` defaults to `false`, according to [this](http://stackoverflow.com/a/8180854). Apparently you can either switch it from app.config or from code directly, maybe that helps?

I'd prefer if it just correctly imported proxy settings from IE instead of having to set it up from environment variables. We already have app.config (immutable) and the settings file (mutable), adding another configuration namespace might confuse the users too much.

**Comment by Tyrrrz** [comment]
@monoludic can you test my current master branch and tell me if it fixes your issue without making the changes in your pull request?

**Comment by monoludic** [comment]
* Setting `WebRequest.DefaultWebProxy` in code works well for all requests. Moreover it simplifies the code.

* I understand that you want to keep settings in 1 or 2 different locations. I read the articles you provided and tested some solutions :
	* `app.config` :` useDefaultCredentials="true"` doesn't works
	* Tried setting `CredentialCache.DefaultNetworkCredentials` in code : doesn't work.
	
* Tried your last master branch : same results
I believe the problem is that the proxy authentication is not linked in any way to my Windows credentials (it is the same login/password for all employees).

Even if proxy is set to use DefaultCredentials, there are no default credentials found ! 
	
I even entered proxy login informations in Windows Credential Manager. No results.

I chose to use HTTP_PROXY because it was already set on my machine and used by other softwares (git, Python pip, etc.). If you don't want to use it maybe we can put those infos in Configuration.dat.

I'm afraid I can't afford to spend much time on this subject. I can still test your next versions !

**Comment by Tyrrrz** [comment]
I see, looks like the default credentials was meant to substitute windows credentials or something. Indeed, it doesn't seem like there's anywhere you can put credentials, not even app.config.

Yes, I think putting the proxy settings in Configuration.dat is the way to go. I understand that it makes it slightly inconvenient having to set it up on a per-app basis, but I think it would be easier for most users, especially those that don't utilize environment variables in any other applications. Later we can override FileSettingsService.Load() to also load some settings from environment variables, in order to encapsulate this behavior.

Also, I haven't checked but it looks like your parsing code will have issues with usernames or passwords that contain `@` or `:`.

I will merge your request and make some changes to accommodate with what I wrote above. Thank you for your contribution!

**Comment by monoludic** [comment]
Thank you for listening my proposal :-)

Indeed my code don't handle special characters. If they are some in the login or password, it appears they should be encoded ([http://superuser.com/a/395177](http://superuser.com/a/395177)).

**Pull request merged**
